apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: k8s-helloworld
  app.kubernetes.io/component: server

resources:
  - deployment.yaml
  - service.yaml
