apiVersion: skaffold/v2beta22
kind: Config
metadata:
  name: k8s-helloworld

build:
  artifacts:
    - image: k8s-helloworld
      context: .
      docker:
        dockerfile: Dockerfile

test:
  - image: k8s-helloworld
    context: test
    structureTests:
      - structure/*

deploy:
  kubeContext: minikube
  kustomize:
    paths:
      - deploy/k8s/overlays/dev

profiles:
- name: gcp
  build:
    googleCloudBuild: {}
