apiVersion: skaffold/v2beta25
kind: Config
metadata:
  name: k8s-helloworld

build:
  artifacts:
  - image: k8s-helloworld
    context: .
    docker:
      dockerfile: Dockerfile

test:
  - image: k8s-helloworld
    context: test
    structureTests:
      - structure/*

deploy:
  kubeContext: minikube
  kustomize:
    paths:
      - .k8s/minikube

profiles:
  - name: gcp
    build:
      googleCloudBuild: {}
