apiVersion: v1
kind: Service
metadata:
  name: k8s-helloworld
spec:
  type: ClusterIP
  selector:
    app: k8s-helloworld
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
