version: '3.8'

services:
  app:
    build:
      context: ../.
    volumes:
      - ./etc:/app/etc:ro
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: dbuser
      POSTGRES_PASSWORD: dbpass
      POSTGRES_DB: sample
    volumes:
      - pgdata:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  pgdata: {}
