apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: data
  app.kubernetes.io/component: database

configMapGenerator:
  - name: postgres-cfg
    literals:
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=dbpass
      - POSTGRES_DB=sample

  - name: pgadmin-servers
    files:
      - "servers.json=pgadmin-servers.json"

resources:
  - deployment.yaml
  - service.yaml
