apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - routing/stripprefix-middleware.yaml
  - routing/traefikservice.yaml
  - routing/ingressroute.yaml
  - jaeger/jaeger.yaml
  - database
